name: Deploy Lambda

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create PocketDimension deployment package
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -r deployment.zip . -i ./lambda/*.js

    - name: Deploy PocketDimension deployment package to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: PocketDimension
        zip_file: deployment.zip
